### ISSUE TITLE
Potential bug / conversion issue

### ISSUE THREAD

**Issue by thibautjombart** [emmanuelparadis/pegas#10]
I have just noticed this:

```
library(pegas)
> data(nancycats)
> hw.test(nancycats, B=0)hw.test(nancycats, B=0)
          chi^2  df  Pr(chi^2 >)
fca8  395.80006 120 0.000000e+00
fca23 239.34221  55 0.000000e+00
fca43 434.33397  45 0.000000e+00
fca45  66.11849  36 1.622163e-03
fca77 270.52066  66 0.000000e+00
fca78 402.80002  28 0.000000e+00
fca90 217.19836  66 0.000000e+00
fca96 193.36764  66 1.965095e-14
fca37 291.00731 153 1.209777e-10
```

Which works; however, when using the same dataset, but this time read using read.genetix:

``` r
> cats <- import2genind(system.file("files/nancycats.gtx",package="adegenet"))

 Converting data from GENETIX to a genind object... 

...done.

> hw.test(cats, B=0)
            chi^2  df  Pr(chi^2 >)
fca8  46504.45655 120 0.000000e+00
fca23  2023.71668  55 0.000000e+00
fca43  7957.23992  45 0.000000e+00
fca45    93.25975  36 5.681616e-07
fca77 21636.11122  66 0.000000e+00
fca78  1072.03868  28 0.000000e+00
fca90 11361.25571  66 0.000000e+00
fca96   825.46134  66 0.000000e+00
fca37  2283.46490 153 0.000000e+00
There were 18 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In O - E : longer object length is not a multiple of shorter object length
2: In (O - E)^2/E :
  longer object length is not a multiple of shorter object length
3: In O - E : longer object length is not a multiple of shorter object length
4: In (O - E)^2/E :
....
```

Looking at why / how the objects are different, I realise the alleles are not sorted in the same way in both datasets. But essentially, the data is identical. 

I suspect as.loci (and the loci class) may assume that alleles are sorted? Does it make sense? In any case, we should address this soon (I am using hw.test in a practical for a workshop next week :-/ )

**Comment by aaron-adamack** [comment]
Crossposting this to the link that Thibaut posted above...

I am running into this bug within PopGenReport. The problem seems to originate within the test.polyploid function that is in the hw.test.loci function in pegas. If I have the alleles 174 and 176, the function generates expected probabilities for the genotypes 174/174, 174/176, and 176/176.  The function goes on to generate observed probabilities. If the allele order is 176 followed by 174, it comes up with observed allele frequencies for 174/174, 176/176 and the new allele combination of 176/174. However, it also retains the allele combination of 174/176 resulting in the observed values (O) having 4 values and the expected values (E) having 3 values, leading to the following error message....
Warning messages:
1: In O - E :
  longer object length is not a multiple of shorter object length
2: In (O - E)^2/E :
  longer object length is not a multiple of shorter object length

**Comment by emmanuelparadis** [comment]
Yes pegas assumes that alleles are ordered in genotypes in "loci" objects. The issue seems to be fixed if the last line in as.loci.genind:

`obj`

is replaced by:

`.check.order.alleles(obj)`

Note that proba.genotype, called by hw.test, always sorts alleles:

``` r
> proba.genotype(c("A", "a"))
 A/A  A/a  a/a 
0.25 0.50 0.25 
> proba.genotype(c("a", "A"))
 A/A  A/a  a/a 
0.25 0.50 0.25
```

Thanks for the report!

**Comment by thibautjombart** [comment]
Yay, thanks @emmanuelparadis for the fix!
