### ISSUE TITLE
enhancement for read.vcf function?

### ISSUE THREAD

**Issue by lduvaux** [emmanuelparadis/pegas#11]
Hi,
I would like to suggest two new features for the `read.vcf` function.
1. the man page states that `In the VCF standard, missing data are represented by a dot and these are read "as is" by the present function without trying to substitute by ‘NA’.` I think this behaviour is really too bad actually since:
   -  `./.` can represent indels as well
   - it makes the resulting `loci` object less compatible with the adegenet `genInd` object (I have to filter and lose some of my data before to be able to use the function `loci2genind`).
   - some analyses being able to deal with missing data (`tab` accessor in adegenet).
2.  it would be great to add an option allowing to filter genotypes based on the `FORMAT` field [(see vcf format 4.2)](http://samtools.github.io/hts-specs/VCFv4.2.pdf). For instance, one may need to replace genotypes by `NA` each time `GQ` or `DP` are below a given threshold (say 30 and 10, respectively).

Would it be complex to add such options? Would the parsing slow down the file reading too much?
I know that plenty of tools already exist to filter vcf outside R but they usually consist into removing bad SNPs (not to replace genotype by NAs). Also, filtering directly using `R` would allow great compatibility with pegas and adegenet without losing any data.
I hope it's not too difficult to implement as I think it would be useful for many people.

Cheers,
Ludovic

**Comment by emmanuelparadis** [comment]
1. Several functions in pegas have the option `na.alleles` (in particular `loci2genind()`) and there is the function `na.omit()` that should solve this first issue.

2. That's exactly what the function `VCFloci()` make possible: it returns a data frame with all information on all loci in the file so that it's possible to read the genotypes for some of them using standard R selection based on logical operations. There is an example in our [2017 paper in MER](https://doi.org/10.1111/1755-0998.12577), and many others in [my book](http://ape-package.ird.fr/PGR.html).
