### ISSUE TITLE
problem with SNP without polymorphism from VCF

### ISSUE THREAD

**Issue by frederic-michaud** [emmanuelparadis/pegas#30]
I notice that the function `glPlot()` does not work on data set where some loci are not polymorphic. More precisely, I'm importing a VCF file, which happens to have some locus who appears as polymorphic but where the actual allele is always the same (I didn't generate the file myself so I'm not sure why this is happening). 
In this case, the dimension of the slot tab is not twice the number of loci (all individual are diploid), and this seems to cause problems at least to the function `glPlot() `:

```
my_loci <- read.vcf("~/Desktop/example2.vcf") #file with some SNP without polymorphim...
# For example, at locus 200, all individuals are G/G
my_genind <- loci2genind(my_loci) 
dim(my_genind$tab)
nLoc(my_genind)
glPlot(my_genind)
```

```
Reading 10000 / 10000 loci.
Done.
duplicate labels detected for some loci; using generic labels[1]    
89 19932  ## dim(my_genind$tab)
10000   ##  nLoc(my_genind)
##Next error is generated by glPlot(my_genind)
Error in image.default(x = 1:nLoc(x), y = 1:nInd(x), z = X, xlab = "SNP index", : dimensions of z are not length(x)(-1) times length(y)(-1)
```

VCF file is very heavy so I cannot join it, but I can try to generate a lighter version if necessary. I'm posting here because I think that the problem comes from loci2genind which is part of pegas, but the problem is made visible by glPlot which is a adgenet function.

**Comment by emmanuelparadis** [comment]
From what I understand, your VCF file has something like REF='A' and ALT='G' (the reference and alternative alleles, respectively) and all genotypes are 0/0 (maybe because some individuals were removed, or because ALT is present in the population at a very low frequency and this is a sample where no heterozygote was observed). This situation is not a problem for `read.vcf` and you get a locus with all genotypes A/A (though you loose the information that there exist another allele on this locus, but you can get this information from the `VCFloci` funtion).

In this situation, the `tab` slot generated by `loci2genind`has only one column for this locus:

```r
R> x <- as.loci( c("A/A", "A/A"))
R> x
Allelic data frame: 2 individuals
                    1 locus
R> loci2genind(x)@tab
  loc1.A
1      2
2      2
```

All that said, `glPlot` needs a `"genlight"` object, while you are producing a `"genind"` one.

**Comment by frederic-michaud** [comment]
Ok, thanks for the explanation about the `tab` slot. 
And sorry for mixing up between `genlight` and `genind`. By curiosity, is there a built-in function to import VCF file into a `genlight` object? This issue is still open: https://github.com/thibautjombart/adegenet/issues/20 so it seems that it's not the case.

**Comment by emmanuelparadis** [comment]
No, not that I know. I think a possible work-around is to convert the VCF to FASTA (it seems samtools can do that) then use `fasta2genlight` in adegenet

**Comment by frederic-michaud** [comment]
Ok. Thanks!

**Comment by knausb** [comment]
Hi @frederic-michaud , if you want to get from VCF to genlight, can I suggest the following.

```
library(vcfR)
vcf <- read.vcfR('myVCFfile.vcf.gz')
myGl <- vcfR2genlight(vcf)
```

There's more at vcfR documentation [Export to genlight and snpclone](https://knausb.github.io/vcfR_documentation/export_genlight_snpclone.html).

**Comment by frederic-michaud** [comment]
Hi. Thanks for the reference. It was useful for me.
