### ISSUE TITLE
hw.test.R problem with data set ncol > 170

### ISSUE THREAD

**Issue by thierrygosselin** [emmanuelparadis/pegas#6]
Hi Emmanuel, in hw.test. R early in the code:

.multinomialCoef <- function(x)
{
    n <- nrow(x)
    numerator <- factorial(ncol(x))
    coef <- numeric(n)
    for (i in seq_len(n))
        coef[i] <- numerator/prod(factorial(tabulate(x[i, ])))
    coef
}

factorial(ncol(x)) seems to be limited to data set with < 170 column. Is that normal ?

Thierry

**Comment by emmanuelparadis** [comment]
Hi Thierry,

This function is not called with the data matrix but with a matrix (x) with genotypes as rows and the different alleles of the genotype as columns. So `ncol(x)` is the ploidy level. Do you analyse a data set where organisms have more than 170 chromosomes?

Anyway, this limitation is because factorial(171) is over the largest number that can be stored with double precision floats. This can be solved by using an initial log-transformation and the function `lfactorial` which computes the factorial on a log-scale. Here is the modified function:

``` r
.multinomialCoef
function(x)
{
    n <- nrow(x)
    numerator <- lfactorial(ncol(x))
    coef <- numeric(n)
    for (i in seq_len(n))
        coef[i] <- numerator - sum(lfactorial(tabulate(x[i, ])))
    exp(coef)
}
```

This gives similar results than the original function:

``` r
> alleles <- paste0("L", 1:2)
> geno <- expand.genotype(length(alleles), ploidy = 170, matrix = TRUE)
> all.equal(pegas:::.multinomialCoef(geno), .multinomialCoef(geno))
[1] TRUE
```

And for more ploidy > 170:

``` r
> geno <- expand.genotype(length(alleles), ploidy = 171, matrix = TRUE)
> head(pegas:::.multinomialCoef(geno))
[1] NaN Inf Inf Inf Inf Inf
Warning messages:
1: In factorial(ncol(x)) :
  valeur d'argument hors intervalle dans 'gammafn'
> head(.multinomialCoef(geno))
[1]          1        171      14535     818805   34389810
[6] 1148619654
```

Does this answer your query?

**Comment by thierrygosselin** [comment]
ok thanks!
I had my data.frame with loci in columns
