### ISSUE TITLE
Results from MMD Function 

### ISSUE THREAD

**Issue by S-Majoros** [emmanuelparadis/pegas#69]
Hello!

I've been using the function MMD to generate mismatch distributions for my data and was hoping I could get some clarification on what the values generated by this function mean. I can interpret the graph, but was wondering what the values included within the object represent. What are w, h, left, top, x, and y? I was hoping to pull out a value if possible that tells me something about the distribution and population that can be used in further analysis. As I am running the analyses on many species and looping through the code, it would be helpful to have a value I could pull out, rather than just manually interpreting each figure. 

Thank you so much!

**Comment by emmanuelparadis** [comment]
Hi, You can look at the code of the function and modify it so that it returns what you are interested in. This code is pretty straightforward, so you should be able to find your way.
Anyway, I think it's a good idea to have some returned value (possibly invisibly, like what `hist()` does). I'll have a look at this when I have more time.
Best,

**Comment by emmanuelparadis** [comment]
`MMD()` now returns (invisibly) a list with the data of the graphical elements (i.e., histogram, empirical density, and expected curve under stable population).
