### ISSUE TITLE
The network algorithm in Haplonet function

### ISSUE THREAD

**Issue by QianGuoPKU** [emmanuelparadis/pegas#72]
Hi,

Thanks for providing such excellent package! I learnt that there are some algorithms for bulding haplotype network, such as minimum spanning tree, median joining network and so on. I also knew the mjn function in pegas package. I have two questions. The first is, what is the network algorithm in Haplonet function? And what are the suitable situations for mjn and Haplonet functions, repectively?

Thanks,
Qian

**Comment by emmanuelparadis** [comment]
Hi, Thank you for your appreciation on the package.
1) The algorithm implemented in `haploNet()` is the "TCS" algorithm:

Templeton, A. R., Crandall, K. A. and Sing, C. F. (1992) A cladistic analysis of phenotypic association with haplotypes inferred from restriction endonuclease mapping and DNA sequence data. III. Cladogram estimation. Genetics, 132, 619-635.

2) MJN works well when the sequences are not too divergent because this algorithm reconstructs "intermediate" sequences (the median-vectors) which can take a lot of time if there are more than a few mutations between two sequences. I don't think there is such a limitation with TCS.

Cheers,
Emmanuel

**Comment by QianGuoPKU** [comment]
> 

Hi Emmanuel,

Appreciate your reply and helpful explanation. I used _pegas_ package to explore my data these days, and was gradually familiar with the functions.  

Expecting other excellent work from you. 

Best,
Qian
