### ISSUE TITLE
Issue with replot() on Windows

### ISSUE THREAD

**Issue by Chatchamew** [emmanuelparadis/pegas#88]
I have tried using replot() on Windows’ RStudio, and the locator does not locate where I click it. Instead, the locator always shift northwestward, making replotting very hard. This does not happen on Mac where the locator is precise. Is there anything I can do?

**Comment by emmanuelparadis** [comment]
I don't use RStudio (and neither Windows), but I think it has a button you can click to have the graphical window "out" of the main GUI (maybe it's called "Zoom"). Otherwise, maybe you can type `windows()` or `X11()` to open a new window (called a graphical device in R's jargon). Hopefully, it won't be embedded in RStudio...

**Comment by Chatchamew** [comment]
Thank you so much for your response.
